apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment-test
spec: 
  selector: 
    matchLabels: 
      app: deployment-test
  template: 
    metadata: 
      labels: 
        app: deployment-test
    spec:
      containers:
      - name: deployment
        image: curlimages/curl
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting at $(date)"
          sleep 20
          echo "Live at $(date)"
          touch /tmp/healthy
          while true; do 
            echo "Running at $(date)"
            sleep 5
          done
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
      - name: cache-volume
        emptyDir: {}
