apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-hooks-app
  namespace: argocd
spec:
  destination:
    namespace: test-hooks
    server: https://my-k8s-cluster:6443
  project: default
  source:
    repoURL: https://github.com/svolland-csgroup/argocd-examples.git
    targetRevision: main
    path: test-hooks-app/simple-app
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
